In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt     
import matplotlib
matplotlib.rcParams['font.family']='Malgun Gothic'
matplotlib.rcParams['axes.unicode_minus']=False

In [ ]:
data={'kor':[80,30,50,70],'eng':[20,90,90,80],
     'math':[33,44,55,66]}  #키값이 리스트인 경우
df =pd.DataFrame(data,index=['aa','bb','cc','dd'])
df

In [ ]:
df.plot(kind='bar')
plt.show()

In [ ]:
df = pd.read_csv('crime_in_seoul.csv',index_col='관서명',engine='python', decimal=',') 
df

In [ ]:
df.iloc[1:,0::2].sum()

In [138]:
df.iloc[2:,1::2]

SyntaxError: unexpected EOF while parsing (<ipython-input-138-27e5c158dd14>, line 1)

In [137]:
df.sum(axis=1)

관서명
중부서      659.920
종로서      646.418
남대문서    2168.153
서대문서    1034.579
혜화서     1460.129
용산서      997.311
성북서     1528.209
동대문서    1175.756
마포서     1402.057
영등포서    1533.497
성동서      871.614
동작서     1114.362
광진서      517.108
서부서     1250.230
강북서      945.431
금천서     1185.397
중랑서     1216.389
강남서     1549.022
관악서     1419.646
강서서      503.281
강동서     1096.326
종암서     2134.015
구로서     1381.774
서초서     1461.441
양천서      920.429
송파서      452.449
노원서     1160.245
방배서     1997.000
은평서      613.824
도봉서      714.853
수서서      972.817
dtype: float64

In [ ]:
df.iloc[2:,1::2].sum()

In [132]:
df3 = {'살인검거율':(round(df['살인 검거'] / pd.to_numeric(df['살인 발생']) * 100,2)), 
         '강도검거율':(round(df['강도 검거'] / pd.to_numeric(df['강도 발생']) * 100,2)),
         '강간검거율':(round(df['강간 검거'] / pd.to_numeric(df['강간 발생']) * 100,2)),
         '절도검거율':(round(df['절도 검거'] / pd.to_numeric(df['절도 발생']) * 100,2)),
         '폭력검거율':(round(df['폭력 검거'] / pd.to_numeric(df['폭력 발생']) * 100,2))
        }
df3 = pd.DataFrame(df3)
df3

       살인검거율   강도검거율   강간검거율     절도검거율     폭력검거율
관서명
중부서   100.00   66.67   61.90  34193.55     86.35
종로서   100.00   83.33   85.22  38598.13     83.72
남대문서    0.00   66.67   70.77  33130.96     91.37
서대문서  100.00   80.00   80.52  40728.48     83.22
혜화서    66.67   80.00   65.62  38061.04  84827.59
용산서   100.00  100.00   89.18  37700.71     83.12
성북서   100.00   50.00   82.56     42.92     85.01
동대문서  100.00  100.00   84.39  41090.36     87.40
마포서   100.00   71.43   84.01  31819.96     84.45
영등포서   85.71   90.91   62.03  32995.95     82.89
성동서   100.00   88.89   94.44  37149.97     86.54
동작서   100.00   55.56   48.77  35442.36     83.09
광진서   100.00  185.71   91.67     42.20     83.05
서부서   100.00   50.00   84.29     35.78     87.08
강북서   114.29   92.86   82.35  43096.23     88.64
금천서   133.33  100.00   80.79  56668.79     86.47
중랑서    92.31   81.82   79.14  38829.04     84.55
강남서   100.00   80.00   75.00  40812.94     87.06
관악서    88.89  116.67   69.06  30561.71     80.11
강서서   114.29  100.00   72.90     60.11     84.75
강동서    75.00  133.33   78.85  33347.42     82.89
종암서   100.00  100.00   82.81     39.90  82758.62
구로서    75.00   73.33   58.36  38072.81     80.88
서초서    57.14   62.50   57.78  45660.95     86.77
양천서   166.67   50.00   87.50  35555.56     80.91
송파서    90.91   76.92   80.91     34.86     84.55
노원서   100.00  100.00   61.42  36525.31     85.53
방배서   200.00  100.00   94.92     28.48     89.76
은평서   100.00   71.43   85.42  38173.52     86.79
도봉서   100.00  111.11  103.92  44967.07     87.63
수서서    70.00  100.00   83.22  46282.14     85.71

In [133]:
df3.idxmax()

살인검거율    방배서
강도검거율    광진서
강간검거율    도봉서
절도검거율    금천서
폭력검거율    혜화서
dtype: object

In [134]:
df4 = {'살인검거율':(df3.sort_values('살인검거율').index[:5]), 
         '강도검거율':(df3.sort_values('강도검거율').index[:5]),
         '강간검거율':(df3.sort_values('강간검거율').index[:5]),
         '절도검거율':(df3.sort_values('절도검거율').index[:5]),
         '폭력검거율':(df3.sort_values('폭력검거율').index[:5])
        }
df4 = pd.DataFrame(df4,index =[1,2,3,4,5])
df4

  살인검거율 강도검거율 강간검거율 절도검거율 폭력검거율
1  남대문서   양천서   동작서   방배서   관악서
2   서초서   서부서   서초서   송파서   구로서
3   혜화서   성북서   구로서   서부서   양천서
4   수서서   동작서   노원서   종암서   강동서
5   구로서   서초서   중부서   광진서  영등포서

In [135]:
df5 = df.iloc[:,0::2]
df5.sum(axis=1)
df5['살인 및 강도 발생율'] = (df5.iloc[:,1]+df5.iloc[:,0])/df5.sum(axis=1)
sr = df5['살인 및 강도 발생율']
sr.sort_values(ascending=False)

관서명
강북서     0.117923
중랑서     0.111120
영등포서    0.106655
도봉서     0.102960
송파서     0.095795
수서서     0.095092
동대문서    0.092058
성동서     0.091408
용산서     0.087716
노원서     0.077655
혜화서     0.075380
은평서     0.075078
구로서     0.074351
종로서     0.071232
강서서     0.069613
마포서     0.068421
광진서     0.068272
양천서     0.067467
관악서     0.060518
강동서     0.058453
강남서     0.055749
금천서     0.055005
동작서     0.046239
중부서     0.044346
서초서     0.042513
서대문서    0.042458
남대문서    0.007430
종암서     0.006644
서부서     0.004473
성북서     0.003831
방배서     0.001586
Name: 살인 및 강도 발생율, dtype: float64